version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/corona-backend-dev
permissions:
  - object: /home/ubuntu/corona-backend-dev
    owner: ubuntu
  - object: /home/ubuntu/corona-backend-dev/*/**
    owner: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before-install-dev.sh
  AfterInstall:
    - location: scripts/after-install-dev.sh
  ApplicationStart:
    - location: scripts/application-start-dev.sh
